name: Update VPM Workflow

on: 
  workflow_dispatch:
  release:
    types: [published, created, edited, unpublished, deleted, released]

# Define main variables
env:
  REPO_OWNER: "SweetForest"                   # The owner of the repository
  REPO_NAME: "VPM"                             # The name of the repository to trigger
  REPO_BRANCH: "main"                          # The branch to use for triggering the workflow
  WORKFLOW_FILENAME: "build-listing.yml"      # The filename of the workflow to trigger
  REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}  # Token for authenticating GitHub API requests
  
jobs:
  dispatch:
    runs-on: ubuntu-latest
    if: github.event.release.draft == false
    steps:
      - name: Trigger VPM Workflow
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.REPO_ACCESS_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: '${{ env.REPO_OWNER }}',          // Specify the repository owner
              repo: '${{ env.REPO_NAME }}',            // Specify the repository name
              workflow_id: '${{ env.WORKFLOW_FILENAME }}', // Specify the workflow filename
              ref: '${{ env.REPO_BRANCH }}'             // Use the specified branch
            });
