name: Trigger VPM Workflow

on: 
  workflow_dispatch:
  workflow_run:
    workflows: [Build and Release]
    types:
      - completed
  release:
    types: [published, created, edited, unpublished, deleted, released]

# Define main variables
env:
  REPO_OWNER: "SweetForest"                   # Change to the owner of the repository
  REPO_NAME: "VPM"                             # Change to the name of the repository you want to trigger
  REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }} # Use the token stored in secrets

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger VPM Workflow
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.REPO_ACCESS_TOKEN }} # Provide the token for authentication
          script: |
            const { owner, repo } = context.repo; // Get the current repository context
            const ref = context.ref; // Get the current ref (branch/tag)
            const response = await github.actions.createWorkflowDispatch({
              owner: process.env.REPO_OWNER,         // Specify the repository owner
              repo: process.env.REPO_NAME,           // Specify the repository name
              workflow_id: 'build-listing.yml',      // Change to the filename of the workflow you want to trigger
              ref: ref                                 // Use the current branch
            });
            console.log('Workflow triggered:', response); // Log the response for debugging
